# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161111_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='groupname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
