# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assetmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_num', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('server_ip', models.CharField(max_length=20, unique=True)),
                ('remote_ip', models.CharField(max_length=20)),
                ('data_center', models.CharField(max_length=20)),
                ('room_num', models.CharField(max_length=20)),
                ('rack_num', models.CharField(max_length=20)),
                ('system_type', models.CharField(default=b'-', max_length=20)),
                ('cputype_num', models.CharField(default=b'-', max_length=20)),
                ('disksize_num', models.CharField(default=b'-', max_length=20)),
                ('memsize_num', models.CharField(default=b'-', max_length=20)),
                ('disk_raid', models.CharField(default=b'-', max_length=20)),
                ('card_type_num', models.CharField(default=b'-', max_length=20)),
                ('power_num', models.CharField(default=b'-', max_length=20)),
                ('service_num', models.CharField(max_length=50, unique=True)),
                ('buy_time', models.CharField(default=b'-', max_length=50)),
                ('expiration_time', models.CharField(default=b'-', max_length=50)),
                ('note', models.CharField(default=b'-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_ip', models.CharField(max_length=20, unique=True)),
                ('app', models.CharField(default=b'-', max_length=50)),
                ('host_name', models.CharField(max_length=20)),
                ('system_version', models.CharField(max_length=20)),
                ('cpu_num', models.CharField(max_length=20)),
                ('disk_size', models.CharField(max_length=20)),
                ('mem_size', models.CharField(max_length=20)),
                ('host_note', models.CharField(default=b'-', max_length=200)),
                ('host_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_set', to='assetmanage.Assetmanage')),
            ],
        ),
    ]
